### ISSUE TITLE
Updating? Not working on WP 4.9.1

### ISSUE THREAD

**Issue by badcat** [bmarshall511/slickity#1]
Hello

Any chance of this being updated to work with WordPress 4.9.1?
Also seems to need an update to he new acf?

thanks

**Comment by bmarshall511** [comment]
Actually working on version 2 now, a complete rewrite, better implementation and options. Hoping to release it by the end of this week.

**Comment by badcat** [comment]
Friday can't come fast enough :)  I updated to my licence of ACF and it's still DOA...  
I'm looking to do the following - do you think Slickity will be able to do it?

* Variable Width for Images
* Nearby images (show 2 etc)
* Full/Adjustable Viewport Height for slider
* Touch enable

thanks!

**Comment by bmarshall511** [comment]
All of the above :)

**Comment by badcat** [comment]
Auto play slideshow?  🥇

**Comment by bmarshall511** [comment]
Yup

**Comment by bmarshall511** [comment]
@badcat You up for some beta testing?

**Comment by badcat** [comment]
@bmarshall511 bring it

**Comment by bmarshall511** [comment]
Excellent! Just pushed up 2.0.0 branch (https://github.com/bmarshall511/slickity/tree/2.0.0). Only things missing from the original are predefined themes and slide schedules. Slide schedule soon to come, theming can now be handled via CSS class options.

Looking forward to your feedback! ...and keep in mind, still early beta.

**Comment by badcat** [comment]
Hmm - the UI al seems fine on the back end. But I'm getting this on the rendered page..

```
<script>
	jQuery(function( $ ) {
	$( '#slickity-1579' ).slick({
    
	responsive: [
	<br />
	<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/.../wp-content/plugins/slickity-2.0.0/slickity.php</b> on line <b>251</b><br />
],
adaptiveHeight: true,autoplay: true,arrows: true,prevArrow: '<button type="button" class="slick-prev">Previous</button>',nextArrow: '<button type="button" class="slick-next">Next</button>',dots: true,infinite: true,mobileFirst: true,slidesToShow: 2,slidesToScroll: 1                  });

	});
</script>
```

**Comment by bmarshall511** [comment]
Just pushed a fix up. Looks like you probably had Responsive check, but no responsive options defined. Let me know if the fix I pushed did the trick.

**Comment by badcat** [comment]
Thanks. It’s working. I think I just need to get my head around the settings.

**Comment by bmarshall511** [comment]
Just released 2.0.0! Gonna close this one out

**Comment by bmarshall511** [comment]
@badcat Making lots of improvements, you can now use prebuilt templates making creating slides easier. Will hopefully get to the scheduler sometime next week... maybe sooner.

**Comment by badcat** [comment]
Looking better - now seeing **$** and **HERE** looping around image content when using the Default Template under Slideshow Options, but Template turn OFF per image. maybe needs a way to block the user from doing this?

**Comment by bmarshall511** [comment]
You using 2.1.0 or 2.2.0? Try updating to 2.2.0 and let me know if you still see it. That was some debugging code I had in previously. 

2.2.0 has a lightbox option now.

**Comment by badcat** [comment]
It still seems to be in 2.2.0, no?

line 280/281  slickity.php

**Comment by bmarshall511** [comment]
You're right! Sorry about that. Must of missed that one. Just pushed the fix up to master.

Thanks again for helping to test? I'll be sure to add you on as a contrib if you'd like and have a WP.org user.

**Comment by badcat** [comment]
thanks @bmarshall511  I haven't really done much here  :)  fwiw, I'm @kelter on wp.org 
I have some other questions - perhaps I can chat off GH?

**Comment by bmarshall511** [comment]
Sure, I'm also on Google hangouts: bmarshall511@gmail.com or on Slickity's Gitter: https://gitter.im/slickity/Lobby#
